merge q fix (#790)

diff --git a/.github/workflows/workflow-pull-request-path.yml b/.github/workflows/workflow-pull-request-path.yml
--- a/.github/workflows/workflow-pull-request-path.yml
+++ b/.github/workflows/workflow-pull-request-path.yml
@@ -8,8 +8,6 @@ on:
     branches:
       - main
   merge_group:
-    branches:
-      - main
 
 permissions:
   id-token: write
@@ -180,6 +178,14 @@ jobs:
     name: End of PR Workflow
     runs-on: ubuntu-latest
     needs: [workflow_variables, behat_branch_environment]
+    if: always()
     steps:
+      - name: Check failure status
+        run: |
+          echo ${{ needs.behat_branch_environment.result }}
+          if [ "${{ needs.behat_branch_environment.result }}" != "success" ]; then
+            echo "❌ Behat branch environment failed"
+            exit 1
+          fi
       - name: End of PR Workflow
-        run: echo "${{ needs.workflow_variables.outputs.version_tag }} tested, built and deployed to Development"
+        run: echo "${{ needs.workflow_variables.outputs.version_tag }} tested, built, and deployed to Development"
