Added end of PR and fixed var name for tag

diff --git a/.github/workflows/workflow-merge-path.yml b/.github/workflows/workflow-merge-path.yml
--- a/.github/workflows/workflow-merge-path.yml
+++ b/.github/workflows/workflow-merge-path.yml
@@ -28,12 +28,12 @@ jobs:
     name: output workflow variables
     outputs:
       build_identifier: "main"
-      version_tag: ${{ steps.semver_tag.outputs.created_tag }}
+      version_tag: ${{ steps.semver_tag.outputs.tag }}
     steps:
       - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
         with:
           fetch-depth: 0
-          
+
       - name: generate semver tag and release
         id: semver_tag
         uses: ministryofjustice/opg-github-actions/actions/semver@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
@@ -128,3 +128,17 @@ jobs:
       current_tag: ${{ needs.workflow_variables.outputs.version_tag }}
       release_tag: releasable
     secrets: inherit
+
+  end_of_pr_workflow:
+    name: End of PR Workflow
+    runs-on: ubuntu-latest
+    needs: [workflow_variables, create_tag_release]
+    if: ${{ always() }}
+    steps:
+      - name: Check workflow result
+        if: ${{ failure() }}
+        run: |
+          echo "A job failed. Marking end-workflow as failed."
+          exit 1
+      - name: End of PR Workflow
+        run: echo "${{ needs.workflow_variables.outputs.version_tag }} tested, built and deployed through preproduction"
