add folder checking

diff --git a/.github/workflows/workflow-pull-request-path.yml b/.github/workflows/workflow-pull-request-path.yml
--- a/.github/workflows/workflow-pull-request-path.yml
+++ b/.github/workflows/workflow-pull-request-path.yml
@@ -35,6 +35,8 @@ jobs:
       version_tag: ${{ steps.semver_tag.outputs.created_tag }}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
       - name: extract variables for workflow
         id: variables
         env:
@@ -52,12 +54,19 @@ jobs:
           echo "" >> $GITHUB_STEP_SUMMARY
           echo "- Branch: ${PARSED_BRANCH}" >> $GITHUB_STEP_SUMMARY
           echo "- Build Identifier: ${BUILD_IDENTIFIER}" >> $GITHUB_STEP_SUMMARY
+      - name: Get Default Bump
+        id: semver_bump
+        run: |
+          pwd
+          ls -alt
+          export bump=$(./scripts/default_bump/bump.sh)
+          echo "default_bump=$(echo ${bump})" >> $GITHUB_OUTPUT
       - name: generate semver tag and release
         id: semver_tag
-        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v3.1.7-fixnexttagde.5 # v3.1.6
+        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@ea1e81f43e7593acd74cc114085930f5f54914a2 # v3.1.7
         with:
           prerelease: true
-          default_bump: "minor"
+          default_bump: ${{ steps.semver_bump.outputs.default_bump }}
       - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
         if: github.event_name == 'pull_request'
         with:
@@ -65,74 +74,74 @@ jobs:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           sync-labels: true
 
-  unit_test_frontend:
-    name: Unit tests on Frontend app
-    uses: ./.github/workflows/_tests-frontend.yml
-
-  build_scan_push_containers:
-    name: Docker Build, Scan and Push
-    uses: ./.github/workflows/_build-push.yml
-    needs: [workflow_variables]
-    with:
-      tag: ${{ needs.workflow_variables.outputs.version_tag }}
-      branch_name: ${{ needs.workflow_variables.outputs.build_identifier }}
-    secrets: inherit
-
-  deploy_to_branch_environment:
-    name: Deploy to Branch Environment
-    needs: [
-      workflow_variables,
-      build_scan_push_containers,
-      unit_test_frontend
-    ]
-    uses: ./.github/workflows/_deploy-infrastructure.yml
-    with:
-      workspace: ${{ needs.workflow_variables.outputs.build_identifier }}
-      account_name: development
-      container_version: ${{ needs.workflow_variables.outputs.version_tag }}
-      terraform_path: environment
-      apply: true
-    secrets: inherit
-
-  plan_development_account:
-    name: Plan against development account
-    needs: [
-      workflow_variables,
-      build_scan_push_containers,
-    ]
-    uses: ./.github/workflows/_deploy-infrastructure.yml
-    with:
-      workspace: development
-      account_name: development
-      container_version: ${{ needs.workflow_variables.outputs.version_tag }}
-      terraform_path: account
-      apply: false
-    secrets: inherit
-
-  behat_branch_environment:
-    name: Branch Environment Behat
-    uses: ./.github/workflows/_tests-behat.yml
-    needs: [workflow_variables,deploy_to_branch_environment]
-    with:
-      workspace_name: ${{ needs.workflow_variables.outputs.build_identifier }}
-      version_tag: ${{ needs.workflow_variables.outputs.version_tag }}
-      base_url: ${{ needs.workflow_variables.outputs.build_identifier }}.serve.opg.service.justice.gov.uk
-      sirius_api_bucket: opg-backoffice-public-api-integration
-      suite: --suite=local
-      account_name: development
-      account_id: 705467933182
-    secrets: inherit
-
-  end_of_pr_workflow:
-    name: End of PR Workflow
-    runs-on: ubuntu-latest
-    needs: [workflow_variables,behat_branch_environment]
-    if: ${{ always() }}
-    steps:
-      - name: Check workflow result
-        if: ${{ failure() }}
-        run: |
-            echo "A job failed. Marking end-workflow as failed."
-            exit 1
-      - name: End of PR Workflow
-        run: echo "${{ needs.workflow_variables.outputs.version_tag }} tested, built and deployed to Development"
+#  unit_test_frontend:
+#    name: Unit tests on Frontend app
+#    uses: ./.github/workflows/_tests-frontend.yml
+#
+#  build_scan_push_containers:
+#    name: Docker Build, Scan and Push
+#    uses: ./.github/workflows/_build-push.yml
+#    needs: [workflow_variables]
+#    with:
+#      tag: ${{ needs.workflow_variables.outputs.version_tag }}
+#      branch_name: ${{ needs.workflow_variables.outputs.build_identifier }}
+#    secrets: inherit
+#
+#  deploy_to_branch_environment:
+#    name: Deploy to Branch Environment
+#    needs: [
+#      workflow_variables,
+#      build_scan_push_containers,
+#      unit_test_frontend
+#    ]
+#    uses: ./.github/workflows/_deploy-infrastructure.yml
+#    with:
+#      workspace: ${{ needs.workflow_variables.outputs.build_identifier }}
+#      account_name: development
+#      container_version: ${{ needs.workflow_variables.outputs.version_tag }}
+#      terraform_path: environment
+#      apply: true
+#    secrets: inherit
+#
+#  plan_development_account:
+#    name: Plan against development account
+#    needs: [
+#      workflow_variables,
+#      build_scan_push_containers,
+#    ]
+#    uses: ./.github/workflows/_deploy-infrastructure.yml
+#    with:
+#      workspace: development
+#      account_name: development
+#      container_version: ${{ needs.workflow_variables.outputs.version_tag }}
+#      terraform_path: account
+#      apply: false
+#    secrets: inherit
+#
+#  behat_branch_environment:
+#    name: Branch Environment Behat
+#    uses: ./.github/workflows/_tests-behat.yml
+#    needs: [workflow_variables,deploy_to_branch_environment]
+#    with:
+#      workspace_name: ${{ needs.workflow_variables.outputs.build_identifier }}
+#      version_tag: ${{ needs.workflow_variables.outputs.version_tag }}
+#      base_url: ${{ needs.workflow_variables.outputs.build_identifier }}.serve.opg.service.justice.gov.uk
+#      sirius_api_bucket: opg-backoffice-public-api-integration
+#      suite: --suite=local
+#      account_name: development
+#      account_id: 705467933182
+#    secrets: inherit
+#
+#  end_of_pr_workflow:
+#    name: End of PR Workflow
+#    runs-on: ubuntu-latest
+#    needs: [workflow_variables,behat_branch_environment]
+#    if: ${{ always() }}
+#    steps:
+#      - name: Check workflow result
+#        if: ${{ failure() }}
+#        run: |
+#            echo "A job failed. Marking end-workflow as failed."
+#            exit 1
+#      - name: End of PR Workflow
+#        run: echo "${{ needs.workflow_variables.outputs.version_tag }} tested, built and deployed to Development"
